'use strict';

module.exports.users = [
  {
    type: 'mentor',
    name: 'Beth Johnson',
    email: 'beth.johnson@hackreactor.com',
    password: '$2a$10$LvfipKxsVRScDkfiSUfefucwtgTrla17luidZE7P13vFWqTPw1qJe',
    location: 'San Francisco',
    role: 'Front end',
    picture: 'http://imgur.com/xEUUtut.jpg',
    techStack: ['React', 'Express', 'Node.js', 'JavaScript'],
    github: 'https://github.com/beth',
    linkedIn: 'https://www.linkedin.com/in/bethjohnson3',
    followers: 26
  },
  {
    type: 'mentor',
    name: 'Benji Marinacci',
    email: 'benji.marinacci@hackreactor.com',
    password: '$2a$10$bPhzdz51BWKiMedaRdYgdeYUuMPeQ1RApalvwzmaUXlk6oNoJWfR6',
    location: 'Palo Alto',
    role: 'Full Stack',
    picture: 'http://imgur.com/iwn6mV5.jpg',
    techStack: ['React', 'Express', 'Node.js', 'JavaScript'],
    github: 'https://github.com/bcmarinacci',
    linkedIn: 'https://www.linkedin.com/in/bcmarinacci',
    followers: 25
  },
  {
    type: 'mentor',
    name: 'Fred Zirdung',
    email: 'fred.zirdung@hackreactor.com',
    password: '$2a$10$kIO9Lc2cU.RMFQ3Vh/d.4OZ6LPb2PUZHtqbfxEIk7XjgIXAJwJUe2',
    location: 'San Francisco',
    role: 'Full Stack',
    picture: 'http://imgur.com/9awfsn2.jpg',
    techStack: ['React', 'Express', 'Node.js', 'JavaScript'],
    github: 'https://github.com/fredx',
    linkedIn: 'https://www.linkedin.com/in/fredzirdung',
    followers: 32
  },
  {
    type: 'mentor',
    name: 'Erik Brown',
    email: 'eric.brown@hackreactor.com',
    password: '$2a$10$QIwi9bkgI5Z/wo5Q7PHcH.tCcy9iGeFYkByAF4OXwbu.UCwhBW6..',
    location: 'San Francisco',
    role: 'Front end',
    picture: 'http://imgur.com/adDa5JU.jpg',
    techStack: ['React', 'Node.js', 'JavaScript'],
    github: 'https://github.com/erikdbrown',
    linkedIn: 'https://www.linkedin.com/in/erikdbrown',
    followers: 24
  },
  {
    type: 'mentor',
    name: 'Tyler Arbus',
    email: 'tyler.arbus@hackreactor.com',
    password: '$2a$10$WsHnHQ9dmqPWcK1X8jYsj.NFl.u6HISeNXHzDjhd4MkqaDQEDwmeG',
    location: 'San Jose',
    role: 'Full Stack',
    picture: 'http://imgur.com/ohFukM2.jpg',
    techStack: ['Angular', 'Node.js', 'JavaScript'],
    github: '',
    linkedIn: '',
    followers: 20
  },
  {
    type: 'mentor',
    name: 'Paul Mills',
    email: 'paul.mills@hackreactor.com',
    password: '$2a$10$MJXtfT8g/KC7BdRXm0K.nu6uTa6rZQqQL1J2zBn1nYZuTBVMuT5GW',
    location: 'San Francisco',
    role: 'Front end',
    picture: 'http://imgur.com/9eJRSav.jpg',
    techStack: ['React', 'Node.js', 'JavaScript'],
    github: '',
    linkedIn: '',
    followers: 21
  },
  {
    type: 'mentor',
    name: 'Alison Zhang',
    email: 'alison.zhang@hackreactor.com',
    password: '$2a$10$OnfA1trzQ4VlH7f/KlwGnOW0m04jyffqMwrBV7OjAX/.1ZXzxph1S',
    location: 'Palo Alto',
    role: 'Full Stack',
    picture: 'http://imgur.com/uz1C3om.jpg',
    techStack: ['React', 'Node.js', 'JavaScript'],
    github: '',
    linkedIn: '',
    followers: 20
  },
  {
    type: 'mentor',
    name: 'Jong Kim',
    email: 'jong.kim@hackreactor.com',
    password: '$2a$10$SHBvPEginR6EFtrHH62eJeKZo3wqAQ95Dz5Ecw8L9NJ6QXNxPbFOm',
    location: 'San Jose',
    role: 'Back end',
    picture: 'http://imgur.com/yTpcGqk.jpg',
    techStack: ['React', 'Node.js', 'JavaScript'],
    github: '',
    linkedIn: '',
    followers: 20
  },
  {
    type: 'padawan',
    name: 'Winston Ku',
    email: 'winston.ku@ku.com',
    password: '$2a$10$SHBvPEginR6EFtrHH62eJeKZo3wqAQ95Dz5Ecw8L9NJ6QXNxPbFOm',
    location: 'San Jose',
  },
  {
    type: 'padawan',
    name: 'Winston Ku',
    email: 'winston.ku@ku.com',
    password: '$2a$10$SHBvPEginR6EFtrHH62eJeKZo3wqAQ95Dz5Ecw8L9NJ6QXNxPbFOm',
    location: 'San Jose',
  },
]
