'use strict';

module.exports.users = [
  {
    type: 'mentor',
    name: 'Beth Johnson',
    email: 'beth.johnson@hackreactor.com',
    password: '$2a$10$LvfipKxsVRScDkfiSUfefucwtgTrla17luidZE7P13vFWqTPw1qJe',
    location: 'San Francisco',
    role: 'Front end',
    picture: 'https://imgur.com/xEUUtut.jpg',
    techStack: ['React', 'Express', 'Node.js', 'JavaScript'],
    github: 'https://github.com/beth',
    linkedIn: 'https://www.linkedin.com/in/bethjohnson3',
    description:'Created automated testing tool to run UI Automated tests on android hand-held devices, compile results of tests into reports, and notify specified persons when testing was complete.',
    followers: 26
  },
  {
    type: 'mentor',
    name: 'Benji Marinacci',
    email: 'benji.marinacci@hackreactor.com',
    password: '$2a$10$bPhzdz51BWKiMedaRdYgdeYUuMPeQ1RApalvwzmaUXlk6oNoJWfR6',
    location: 'Palo Alto',
    role: 'Full Stack',
    picture: 'https://imgur.com/iwn6mV5.jpg',
    techStack: ['React', 'Express', 'Node.js', 'JavaScript'],
    github: 'https://github.com/bcmarinacci',
    linkedIn: 'https://www.linkedin.com/in/bcmarinacci',
    description: 'I worked with Benji while he was a student and a Fellow at MakerSquare. He is brilliant.',
    followers: 25
  },
  {
    type: 'mentor',
    name: 'Fred Zirdung',
    email: 'fred.zirdung@hackreactor.com',
    password: '$2a$10$kIO9Lc2cU.RMFQ3Vh/d.4OZ6LPb2PUZHtqbfxEIk7XjgIXAJwJUe2',
    location: 'San Francisco',
    role: 'Full Stack',
    picture: 'https://imgur.com/9awfsn2.jpg',
    techStack: ['React', 'Express', 'Node.js', 'JavaScript'],
    github: 'https://github.com/fredx',
    linkedIn: 'https://www.linkedin.com/in/fredzirdung',
    description: 'From the very beginning, Fred has shown himself to be an extremely capable manager and mentor.',
    followers: 32
  },
  {
    type: 'mentor',
    name: 'Erik Brown',
    email: 'eric.brown@hackreactor.com',
    password: '$2a$10$QIwi9bkgI5Z/wo5Q7PHcH.tCcy9iGeFYkByAF4OXwbu.UCwhBW6..',
    location: 'San Francisco',
    role: 'Front end',
    picture: 'https://imgur.com/adDa5JU.jpg',
    techStack: ['React', 'Node.js', 'JavaScript'],
    github: 'https://github.com/erikdbrown',
    linkedIn: 'https://www.linkedin.com/in/erikdbrown',
    description:'I\'m a product-driven software engineer, focused on building and supporting applications that have a social or civic impact.',
    followers: 24
  },
  {
    type: 'mentor',
    name: 'Tyler Arbus',
    email: 'tyler.arbus@hackreactor.com',
    password: '$2a$10$WsHnHQ9dmqPWcK1X8jYsj.NFl.u6HISeNXHzDjhd4MkqaDQEDwmeG',
    location: 'San Jose',
    role: 'Full Stack',
    picture: 'https://imgur.com/ohFukM2.jpg',
    techStack: ['Angular', 'Node.js', 'JavaScript'],
    description: 'I graduated from business school in 2014, and then worked as a management consultant for two and a half years.',
    github:'https://github.com/tylerarbus',
    linkedIn: 'https://www.linkedin.com/in/tylerarbus/',
    followers: 20
  },
  {
    type: 'mentor',
    name: 'Paul Mills',
    email: 'paul.mills@hackreactor.com',
    password: '$2a$10$MJXtfT8g/KC7BdRXm0K.nu6uTa6rZQqQL1J2zBn1nYZuTBVMuT5GW',
    location: 'San Francisco',
    role: 'Front end',
    picture: 'https://imgur.com/9eJRSav.jpg',
    techStack: ['React', 'Node.js', 'JavaScript'],
    description: 'I graduated from Colgate University in 2012. Most recently I worked as a Marketing Associate for an edtech company in the Bay Area for about two years.',
    github: 'https://github.com/pmillssf',
    linkedIn: 'https://www.linkedin.com/in/pauldfmills/',
    followers: 21
  },
  {
    type: 'mentor',
    name: 'Alison Zhang',
    email: 'alison.zhang@hackreactor.com',
    password: '$2a$10$OnfA1trzQ4VlH7f/KlwGnOW0m04jyffqMwrBV7OjAX/.1ZXzxph1S',
    location: 'Palo Alto',
    role: 'Full Stack',
    picture: 'https://imgur.com/uz1C3om.jpg',
    techStack: ['React', 'Node.js', 'JavaScript'],
    github: 'https://github.com/alisonzthu',
    linkedIn: 'www.linkedin.com/in/xueying-alison-z',
    description: 'I wrote a GUI-based calculator and a library management system with Java before. They are both quite simple though.',
    followers: 20
  },
  {
    type: 'mentor',
    name: 'Jong Kim',
    email: 'jong.kim@hackreactor.com',
    password: '$2a$10$SHBvPEginR6EFtrHH62eJeKZo3wqAQ95Dz5Ecw8L9NJ6QXNxPbFOm',
    location: 'San Jose',
    role: 'Back end',
    picture: 'https://imgur.com/yTpcGqk.jpg',
    techStack: ['React', 'Node.js', 'JavaScript'],
    github: 'https://github.com/ijongkim',
    linkedIn: 'https://www.linkedin.com/in/ijongkim',
    description: 'I am always looking for things to improve within a given process or organization.',
    followers: 20
  },
  {
    type: 'padawan',
    name: 'Winston Ku',
    email: 'winston.ku@ku.com',
    password: '$2a$10$SHBvPEginR6EFtrHH62eJeKZo3wqAQ95Dz5Ecw8L9NJ6QXNxPbFOm',
    location: 'San Jose',
  },
  {
    type: 'padawan',
    name: 'Winston Ku',
    email: 'winston.ku@ku.com',
    password: '$2a$10$SHBvPEginR6EFtrHH62eJeKZo3wqAQ95Dz5Ecw8L9NJ6QXNxPbFOm',
    location: 'San Jose',
  }
]
