'use strict';

module.exports = [
  {
    name: 'Beth Johnson',
    location: 'SF',
    picture: 'http://imgur.com/xEUUtut.jpg',
    React: true,
    Angular: false,
    Backbone: false,
    Express: true,
    Redux: false,
    Authorization: false,
    TDD: true,
    'Mocha/Chai': true,
    'React Native': false,
    'Node': true,
  },
  {
    name: 'Benji Marinacci',
    location: 'San Jose',
    picture: 'http://imgur.com/iwn6mV5.jpg',
    React: true,
    Angular: true,
    Backbone: true,
    Express: true,
    Redux: false,
    Authorization: false,
    TDD: false,
    'Mocha/Chai': false,
    'React Native': true,
    'Node': true,
  },
  {
    name: 'Fred Zirdung',
    location: 'SF',
    picture: 'http://imgur.com/9awfsn2.jpg',
    React: true,
    Angular: false,
    Backbone: true,
    Express: true,
    Redux: true,
    Authorization: false,
    TDD: true,
    'Mocha/Chai': true,
    'React Native': false,
    'Node': false,
  },
  {
    name: 'Eric Brown',
    location: 'Palo Alto',
    picture: 'http://imgur.com/adDa5JU.jpg',
    React: true,
    Angular: false,
    Backbone: false,
    Express: true,
    Redux: true,
    Authorization: false,
    TDD: true,
    'Mocha/Chai': true,
    'React Native': false,
    'Node': true,
  },
  {
    name: 'Tyler Arbus',
    location: 'SF',
    picture: 'http://imgur.com/ohFukM2.jpg',
    React: false,
    Angular: true,
    Backbone: false,
    Express: true,
    Redux: false,
    Authorization: false,
    TDD: true,
    'Mocha/Chai': true,
    'React Native': false,
    'Node': true,
  },
  {
    name: 'Paul Mills',
    location: 'Palo Alto',
    picture: 'http://imgur.com/9eJRSav.jpg',
    React: true,
    Angular: false,
    Backbone: false,
    Express: true,
    Redux: false,
    Authorization: false,
    TDD: true,
    'Mocha/Chai': true,
    'React Native': true,
    'Node': true,
  },
  {
    name: 'Alison Zhang',
    location: 'San Jose',
    picture: 'http://imgur.com/uz1C3om.jpg',
    React: false,
    Angular: false,
    Backbone: false,
    Express: true,
    Redux: true,
    Authorization: false,
    TDD: true,
    'Mocha/Chai': false,
    'React Native': false,
    'Node': true,
  },
  {
    name: 'Jong Kim',
    location: 'San Jose',
    picture: 'http://imgur.com/yTpcGqk.jpg',
    React: true,
    Angular: true,
    Backbone: true,
    Express: false,
    Redux: false,
    Authorization: false,
    TDD: true,
    'Mocha/Chai': true,
    'React Native': false,
    'Node': false,
  },
]
