'use strict';

module.exports = [
  {
    name: 'Beth Johnson',
    location: 'SF',
    picture: 'http://imgur.com/xEUUtut.jpg',
    react: true,
    angular: false,
    backbone: false,
    express: true,
    redux: false,
    authorization: false,
    TDD: true,
    'mocha/chai': true,
    'react native': false,
    'Node': true,
  },
  {
    name: 'Benji Marinacci',
    location: 'San Jose',
    picture: 'http://imgur.com/iwn6mV5.jpg',
    react: true,
    angular: true,
    backbone: true,
    express: true,
    redux: false,
    authorization: false,
    TDD: false,
    'mocha/chai': false,
    'react native': true,
    'Node': true,
  },
  {
    name: 'Fred Zirdung',
    location: 'SF',
    picture: 'http://imgur.com/9awfsn2.jpg',
    react: true,
    angular: false,
    backbone: true,
    express: true,
    redux: true,
    authorization: false,
    TDD: true,
    'mocha/chai': true,
    'react native': false,
    'Node': false,
  },
  {
    name: 'Eric Brown',
    location: 'Palo Alto',
    picture: 'http://imgur.com/adDa5JU.jpg',
    react: true,
    angular: false,
    backbone: false,
    express: true,
    redux: true,
    authorization: false,
    TDD: true,
    'mocha/chai': true,
    'react native': false,
    'Node': true,
  },
  {
    name: 'Tyler Arbus',
    location: 'SF',
    picture: 'http://imgur.com/ohFukM2.jpg',
    react: true,
    angular: true,
    backbone: false,
    express: true,
    redux: false,
    authorization: false,
    TDD: true,
    'mocha/chai': true,
    'react native': false,
    'Node': true,
  },
  {
    name: 'Paul Mills',
    location: 'Palo Alto',
    picture: 'http://imgur.com/9eJRSav.jpg',
    react: true,
    angular: false,
    backbone: false,
    express: true,
    redux: false,
    authorization: false,
    TDD: true,
    'mocha/chai': true,
    'react native': true,
    'Node': true,
  },
  {
    name: 'Alison Zhang',
    location: 'San Jose',
    picture: 'http://imgur.com/uz1C3om.jpg',
    react: true,
    angular: false,
    backbone: false,
    express: true,
    redux: true,
    authorization: false,
    TDD: true,
    'mocha/chai': true,
    'react native': false,
    'Node': true,
  },
  {
    name: 'Jong Kim',
    location: 'San Jose',
    picture: 'http://imgur.com/yTpcGqk.jpg',
    react: true,
    angular: false,
    backbone: true,
    express: false,
    redux: false,
    authorization: false,
    TDD: true,
    'mocha/chai': true,
    'react native': false,
    'Node': false,
  },
]